# Utiliser l'image de base Elixir 1.17.3 avec Erlang 27 sur Alpine Linux
FROM elixir:1.17.3-alpine

# Installer les dépendances du système
RUN apk add --no-cache build-base nodejs npm git postgresql-client

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer Hex et Rebar pour la gestion des dépendances Elixir
RUN mix local.hex --force && mix local.rebar --force

# Copier les fichiers mix pour installer les dépendances
COPY mix.exs mix.lock ./

# Récupérer et installer les dépendances Elixir
RUN mix deps.get

# Copier le reste de l'application dans le conteneur
COPY . .

# Compiler l'application
RUN mix compile

# Exposer le port 4000 pour Phoenix
EXPOSE 4000

# Démarrer le serveur Phoenix
CMD ["mix", "phx.server"]
